mackerelio-labs/terraform-provider-mackerel

.golangci.yml

I created this PR https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/44 .
Although this pull request uses GetOkExists to fix bug, GetOkExists is deprecated now.
So, I updated .golangci.yml to ignore warning of deprecated Error.

add exclude list of issue to ignore deprecate error of GetOkExists

---

mackerel/resource_mackerel_monitor.go

When warning and critical of service metric monitoring as zero, they are set as null because GetOK returns zero as false.
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/schema#ResourceData.GetOk
To allow them to set zero as value, I suggest to use GetOkExists instead of GetOk.
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/schema#ResourceData.GetOkExists
I'd appreciate it if you could give me your opinion 🙏

bugfix: use GetOkExists to set zero as value

---

mackerel/resource_mackerel_service_metadata.go
mackerel/resource_mackerel_service_metadata_test.go

fix error message for service metadata import

---

mackerel/provider.go

Since Terraform 0.14, make it easier to redact sensitive information in Terraform workflows. and we can define as sensitive at provider schema.
i think api_key is always secret data. so, I want the provider side to treat it as sensitive.

set Sensitive to api_key

---

mackerel/resource_mackerel_monitor.go
mackerel/resource_mackerel_monitor_test.go

To change the "metric" parameter in host and service metric monitor, destroy and create are required, so I added "ForceNew".
Also, I changed the test so that TestAcc will fail if there is no "ForceNew."
<details>
<summary>test acc (not "ForceNew")</summary>
```
=== CONT  TestAccMackerelMonitor_ServiceMetric
testing.go:705: Step 1 error: errors during apply:
Error: API request failed: cannot change target.
on /tmp/tf-test228754959/main.tf line 6:
(source code not available)
--- PASS: TestAccMackerelDowntime_ResourceNotFound (0.57s)
=== CONT  TestAccMackerelChannel_Email
--- PASS: TestAccDataSourceMackerelMonitorExternal (1.40s)
=== CONT  TestAccMackerelChannel_ResourceNotFound
--- FAIL: TestAccMackerelMonitor_ServiceMetric (1.44s)
=== CONT  TestAccMackerelAlertGroupSetting
=== CONT …
```

changing the "metric" parameter requires destroy and create

---

docs/resources/service.md

I think `name` is the name of service, not the role. I propose changes. Please review it.

fix documentation about resource mackerel_service

---

docs/resources/channel.md

I fixed typo in the documentation.Please review it.

fix typo about mackerel_channel documantaion

---

README.md
docs/index.md
mackerel/provider.go
mackerel/provider_test.go

I added *MACKEREL_APIKEY* environment variable.
Mackerel tools, such as *mkr*, uses *MACKEREL_APIKEY* environment variable.

add MACKEREL_APIKEY as an alias of MACKEREL_API_KEY

---

main.go

Added a debug mode to debug the provider using [go\-delve/delve](https://github.com/go-delve/delve), etc.
```console
dlv debug -- -debug
```
Usage:
- Start the provider with the `-debug` flag.
- Copy the output `TF_REATTACH_PROVIDERS`.
- Open a new terminal and export the copied `TF_REATTACH_PROVIDERS`.
- Run terraform.

add debug-mode

---

.github/workflows/ci.yml
.github/workflows/release.yml
go.mod
go.sum

- Resolved the following errors. (bump `github.com/hashicorp/terraform-json` and exec `go mod tidy`)
> Error retrieving state, there may be dangling resources: unsupported state format version: expected ["0.1" "0.2"], got "1.0"
- Don't need to test with multiple versions of golang, so we'll focus on 1.17.

Resolve errors in tests and set golang version only 1.17

---

Makefile
mackerel/resource_mackerel_aws_integration.go

```
$ make testacc TESTS=TestAccMackerelAWSIntegrationIAMRole
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelAWSIntegrationIAMRole -timeout 120m
=== RUN   TestAccMackerelAWSIntegrationIAMRole
=== PAUSE TestAccMackerelAWSIntegrationIAMRole
=== CONT  TestAccMackerelAWSIntegrationIAMRole
--- PASS: TestAccMackerelAWSIntegrationIAMRole (8.78s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel       9.447s
```
other log: https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/106#issue-1364210232

Add support for Route53, Amazon Connect, DocumentDB, CodeBuild to Integration

---

docs/resources/monitor.md

When I was making a service metric monitor using `missing_duration_warning` , I didn't know the limitations of the values (i.e. needs to be between 10 minutes and 1 week). The [documentation](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/monitor#service_metric-1) did not explain it so I added to the docs with this pull request.

[Docs] Add to the docs about the validations that some resource fields have.

---

mackerel/resource_mackerel_aws_integration.go

same as: https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/53
```
$ make testacc TESTS=TestAccMackerelAWSIntegration                     
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelAWSIntegration -timeout 120m
=== RUN   TestAccMackerelAWSIntegrationIAMRole
=== PAUSE TestAccMackerelAWSIntegrationIAMRole
=== RUN   TestAccMackerelAWSIntegrationCredentials
=== PAUSE TestAccMackerelAWSIntegrationCredentials
=== CONT  TestAccMackerelAWSIntegrationIAMRole
=== CONT  TestAccMackerelAWSIntegrationCredentials
--- PASS: TestAccMackerelAWSIntegrationCredentials (7.87s)
--- PASS: TestAccMackerelAWSIntegrationIAMRole (7.88s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel8.404s
...
```

aws_integration: set `Sensitive` to `key`

---

README.md

fix status badges for changing actions names
---
```
...
```

fix status badges

---

mackerel/resource_mackerel_dashboard.go

- resolve #137
```
$ make testacc TESTS=TestAccMackerelDashboardGraph
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelDashboardGraph -timeout 120m
=== RUN   TestAccMackerelDashboardGraph
=== PAUSE TestAccMackerelDashboardGraph
=== CONT  TestAccMackerelDashboardGraph
--- PASS: TestAccMackerelDashboardGraph (4.35s)
PASS
ok  	github.com/mackerelio-labs/terraform-provider-mackerel/mackerel	4.932s
```

fixed panic when range is not set

---

mackerel/resource_mackerel_dashboard.go

The following code is inappropriate but the provider accepts it.
```hcl
markdown {
title    = ""
markdown = "hello, world"
layout {
x      = 12
y      = 7
width  = 12
height = 8
}
layout {
x      = 12
y      = 7
width  = 12
height = 8
}
}
```
By specifying MaxItem in the list type schema, the above code will not be accepted at `terraform plan`.
```
terraform plan
╷
│ Error: Too many layout blocks
│
│   on main.tf line 148, in resource "mackerel_dashboard" "this":
│  148:       layout {
│
│ No more than 1 "layout" blocks are allowed
╵
```
```
$ make testacc TESTS=TestAccMackerelDashboardGraph
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelDashboardGraph -timeout 120m
=== RUN   TestAccMackerelDashboardGraph
=== PAUSE TestAccMackerelDashboardGraph
=== …
```

add MaxItems for list in dashboard schema

---

.github/workflows/lint.yml
mackerel/data_source_mackerel_aws_integration.go
mackerel/data_source_mackerel_aws_integration_test.go
mackerel/resource_mackerel_aws_integration.go
mackerel/resource_mackerel_aws_integration_test.go
mackerel/structure_flattens.go

```
make testacc TESTS=TestAccDataSourceMackerelAWSIntegrationIAMRole
TF_ACC=1 go test -v ./mackerel/... -run TestAccDataSourceMackerelAWSIntegrationIAMRole -timeout 120m
=== RUN   TestAccDataSourceMackerelAWSIntegrationIAMRole
=== PAUSE TestAccDataSourceMackerelAWSIntegrationIAMRole
=== CONT  TestAccDataSourceMackerelAWSIntegrationIAMRole
--- PASS: TestAccDataSourceMackerelAWSIntegrationIAMRole (3.57s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 4.049s
```

added retire automatically for RDS

---

docs/resources/dashboard.md

Since it is mandatory to enter a title for dashboard widgets, we added Required on the document.
https://mackerel.io/api-docs/entry/dashboards#widget
```
...
```

chore(doc): Require widget title input.

---

go.mod
go.sum
mackerel/data_source_mackerel_monitor.go
mackerel/data_source_mackerel_monitor_test.go
mackerel/resource_mackerel_monitor.go
mackerel/resource_mackerel_monitor_test.go
mackerel/structure_flattens.go

```
$ make testacc TESTS="'TestAcc(DataSourceMackerelMonitorQuery|MackerelMonitor_Query)'"
TF_ACC=1 go test -v ./mackerel/... -run 'TestAcc(DataSourceMackerelMonitorQuery|MackerelMonitor_Query)' -timeout 120m
=== RUN   TestAccDataSourceMackerelMonitorQuery
=== PAUSE TestAccDataSourceMackerelMonitorQuery
=== RUN   TestAccMackerelMonitor_Query
=== PAUSE TestAccMackerelMonitor_Query
=== CONT  TestAccDataSourceMackerelMonitorQuery
=== CONT  TestAccMackerelMonitor_Query
--- PASS: TestAccDataSourceMackerelMonitorQuery (4.40s)
--- PASS: TestAccMackerelMonitor_Query (7.73s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 8.363s
```

Added support for monitors with PromQL

---

docs/data-sources/aws_integration.md
docs/resources/aws_integration.md
mackerel/data_source_mackerel_aws_integration.go
mackerel/resource_mackerel_aws_integration.go
mackerel/structure_flattens.go

```
$ make testacc TESTS=TestAccMackerelAWSIntegrationIAMRole
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelAWSIntegrationIAMRole -timeout 120m
=== RUN   TestAccMackerelAWSIntegrationIAMRole
=== PAUSE TestAccMackerelAWSIntegrationIAMRole
=== CONT  TestAccMackerelAWSIntegrationIAMRole
--- PASS: TestAccMackerelAWSIntegrationIAMRole (5.32s)
PASS
ok  	github.com/mackerelio-labs/terraform-provider-mackerel/mackerel	5.680s
```

Allow ElastiCache to retire automatically

---

docs/data-sources/monitor.md
docs/resources/monitor.md

This pull request adds the documentation that was missing in PR #201.
```
$ . make testacc TESTS=TestAccXXX
...
```
Since this pull request only involves documentation changes and does not include any code modifications, acceptance tests are not required.

Add docs for monitors with a query

---

.github/workflows/acceptance-test.yml
.github/workflows/lint.yml
.github/workflows/release.yml
go.mod
go.sum

This PR updates go version.
I introduced `slices` in #209, but go version is still v1.21.x, which broke CI.
I'm going to fix that.

Build with go v1.22

---

internal/provider/provider_test.go

fix: typo MACKEREL_APIKEY

---

docs/data-sources/dashboard.md
docs/resources/dashboard.md
go.mod
go.sum
mackerel/data_source_mackerel_dashboard.go
mackerel/data_source_mackerel_dashboard_test.go
mackerel/resource_mackerel_dashboard.go
mackerel/resource_mackerel_dashboard_test.go
mackerel/structure_flattens.go

```
$ make testacc TESTS="'TestAcc(DataSource)?MackerelDashboard(Graph|Value)'"
TF_ACC=1 go test -v ./mackerel/... -run 'TestAcc(DataSource)?MackerelDashboard(Graph|Value)' -timeout 120m
=== RUN   TestAccDataSourceMackerelDashboardGraph
=== PAUSE TestAccDataSourceMackerelDashboardGraph
=== RUN   TestAccDataSourceMackerelDashboardValue
=== PAUSE TestAccDataSourceMackerelDashboardValue
=== RUN   TestAccMackerelDashboardGraph
=== PAUSE TestAccMackerelDashboardGraph
=== RUN   TestAccMackerelDashboardValue
=== PAUSE TestAccMackerelDashboardValue
=== CONT  TestAccDataSourceMackerelDashboardGraph
=== CONT  TestAccMackerelDashboardGraph
=== CONT  TestAccDataSourceMackerelDashboardValue
=== CONT  TestAccMackerelDashboardValue
--- PASS: …
```

Labeled metrics for dashboards

---

docs/resources/monitor.md
mackerel/data_source_mackerel_monitor.go
mackerel/data_source_mackerel_monitor_test.go
mackerel/resource_mackerel_monitor.go
mackerel/resource_mackerel_monitor_test.go
mackerel/structure_flattens.go

I added `mackerel_monitor.connectivity.0.alert_status_on_gone` to support `AlertStatusOnGone` for connectivity monitor.
https://mackerel.io/ja/api-docs/entry/monitors#create:~:text=%E3%83%AB%E3%83%BC%E3%83%AB%E3%81%AE%E3%83%A1%E3%83%A2%E3%80%82-,alertStatusOnGone,-string
Please review the code :pray:
```console
$ make testacc TESTS=TestAccMackerelMonitor_Connectivity
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelMonitor_Connectivity -timeout 120m
=== RUN   TestAccMackerelMonitor_Connectivity
=== PAUSE TestAccMackerelMonitor_Connectivity
=== CONT  TestAccMackerelMonitor_Connectivity
--- PASS: TestAccMackerelMonitor_Connectivity (6.38s)
PASS
ok  	github.com/mackerelio-labs/terraform-provider-mackerel/mackerel	6.765s
$ make testacc …
```

Add support for AlertStatusOnGone in mackerel_monitor connectivity resource

---

go.mod
go.sum
internal/mackerel/service_metadata.go
internal/mackerel/service_metadata_test.go
internal/provider/data_source_mackerel_metadata_test.go
internal/provider/data_source_mackerel_service_metadata.go
internal/provider/provider.go
internal/provider/resource_mackerel_service_metadata.go
internal/provider/resource_mackerel_service_metadata_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"^TestAcc(DataSourceMackerelService(NotMatchAnyService)?|MackerelService)$$"'
TF_ACC=1 go test -v ./mackerel/... -run "^TestAcc(DataSourceMackerelService(NotMatchAnyService)?|MackerelService)$" -timeout 120m
2024/06/26 16:35:58 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelService
=== PAUSE TestAccDataSourceMackerelService
=== RUN   TestAccDataSourceMackerelServiceNotMatchAnyService
=== PAUSE TestAccDataSourceMackerelServiceNotMatchAnyService
=== RUN   TestAccMackerelService
=== PAUSE TestAccMackerelService
=== CONT  TestAccDataSourceMackerelService
=== CONT  TestAccMackerelService
=== CONT …
```

Reimplement service metadata resources and data sources with tf-framework

---

internal/mackerel/service_metric_names.go
internal/mackerel/service_metric_names_test.go
internal/provider/data_source_mackerel_service_metric_names.go
internal/provider/data_source_mackerel_service_metric_names_test.go
internal/provider/provider.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='AccDataSourceMackerelServiceMetricNames'
TF_ACC=1 go test -v ./mackerel/... -run AccDataSourceMackerelServiceMetricNames -timeout 120m
2024/06/26 18:10:02 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelServiceMetricNames
=== PAUSE TestAccDataSourceMackerelServiceMetricNames
=== CONT  TestAccDataSourceMackerelServiceMetricNames
--- PASS: TestAccDataSourceMackerelServiceMetricNames (5.23s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 6.606s
```

Reimplement service metric names with tf-framework

---

.github/workflows/release.yml

see https://goreleaser.com/deprecations/#-rm-dist
```
...
```

replace deprecated option `--rm-dist` with `--clean`

---

.goreleaser.yml

`changelog.skip` is removed 2024-05-26 (v2.0).
https://goreleaser.com/deprecations/?h=changelog.skip#changelogskip
```
...
```

changelog.skip → changelog.disable

---

internal/mackerel/notification_group.go
internal/mackerel/notification_group_test.go
internal/provider/data_source_mackerel_notification_group.go
internal/provider/data_source_mackerel_notification_group_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_notification_group.go
internal/provider/resource_mackerel_notification_group_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"TestAcc(DataSource)?MackerelNotificationGroup"'
TF_ACC=1 go test -v ./mackerel/... -run "TestAcc(DataSource)?MackerelNotificationGroup" -timeout 120m
2024/07/03 20:27:09 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelNotificationGroup
=== PAUSE TestAccDataSourceMackerelNotificationGroup
=== RUN   TestAccMackerelNotificationGroup
=== PAUSE TestAccMackerelNotificationGroup
=== CONT  TestAccDataSourceMackerelNotificationGroup
=== CONT  TestAccMackerelNotificationGroup
--- PASS: TestAccDataSourceMackerelNotificationGroup (6.15s)
--- PASS: TestAccMackerelNotificationGroup (10.66s)
PASS
ok …
```

Reimplement notification groups with tf-framework

---

internal/mackerel/role.go
internal/mackerel/role_test.go
internal/provider/data_source_mackerel_role.go
internal/provider/data_source_mackerel_role_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_role.go
internal/provider/resource_mackerel_role_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"TestAcc(DataSource)?MackerelRole$$"'
TF_ACC=1 go test -v ./mackerel/... -run "TestAcc(DataSource)?MackerelRole$" -timeout 120m
2024/07/04 19:33:25 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelRole
=== PAUSE TestAccDataSourceMackerelRole
=== RUN   TestAccMackerelRole
=== PAUSE TestAccMackerelRole
=== CONT  TestAccDataSourceMackerelRole
=== CONT  TestAccMackerelRole
--- PASS: TestAccDataSourceMackerelRole (5.28s)
--- PASS: TestAccMackerelRole (9.86s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 11.211s
```

Reimplement roles with tf-framework

---

internal/mackerel/role_metadata.go
internal/mackerel/role_metadata_test.go
internal/provider/data_source_mackerel_role_metadata.go
internal/provider/data_source_mackerel_role_metadata_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_role_metadata.go
internal/provider/resource_mackerel_role_metadata_test.go
mackerel/data_source_mackerel_role_metadata_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"TestAcc(DataSource)?MackerelRoleMetadata"'
TF_ACC=1 go test -v ./mackerel/... -run "TestAcc(DataSource)?MackerelRoleMetadata" -timeout 120m
2024/08/07 17:16:18 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelRoleMetadata
=== PAUSE TestAccDataSourceMackerelRoleMetadata
=== RUN   TestAccMackerelRoleMetadata
=== PAUSE TestAccMackerelRoleMetadata
=== CONT  TestAccDataSourceMackerelRoleMetadata
=== CONT  TestAccMackerelRoleMetadata
--- PASS: TestAccDataSourceMackerelRoleMetadata (6.20s)
--- PASS: TestAccMackerelRoleMetadata (11.06s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 12.943s
```

Reimplement role metadata with tf-framework

---

internal/typeutil/floatstring.go
internal/typeutil/floatstring_test.go

Part of #233.
Some attributes on monitors uses strings to represent float values. To handle such values, this PR introduces a new [Custom Type](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/custom) which stores numbers as strings.

Add FloatStringType

---

mackerel/provider.go

Fixes: #223
When using `Required` and `DefaultFunc` at the same time, the attribute may become Optional depending on the result returned by `DefaultFunc`([FYI](https://github.com/hashicorp/terraform-plugin-sdk/blob/4c604df5f03572d01e7c32777b339519213eb475/helper/schema/core_schema.go#L140-L152)). This makes the schema unstable.
This PR fixes this behaviour by making `api_key` optional. Validations for `api_key` will be performed at provider initialization time.
```
$ make testacc TESTS='TestAccMackerelService'
TF_ACC=1 go test -v ./mackerel/... -run TestAccMackerelService -timeout 120m
=== RUN   TestAccMackerelServiceMetadata
=== PAUSE TestAccMackerelServiceMetadata
=== RUN   TestAccMackerelService
=== PAUSE TestAccMackerelService
=== CONT …
```

Make the provider schema stable for environment variables

---

internal/provider/data_source_mackerel_monitor.go
internal/provider/data_source_mackerel_monitor_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_monitor.go
internal/provider/resource_mackerel_monitor_test.go
mackerel/provider.go
mackerel/resource_mackerel_monitor_test.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"Acc(DataSource)?MackerelMonitor"'
TF_ACC=1 go test -v ./mackerel/... -run "Acc(DataSource)?MackerelMonitor" -timeout 120m
2024/08/19 11:47:38 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelMonitorHostMetric
=== PAUSE TestAccDataSourceMackerelMonitorHostMetric
=== RUN   TestAccDataSourceMackerelMonitorConnectivity
=== PAUSE TestAccDataSourceMackerelMonitorConnectivity
=== RUN   TestAccDataSourceMackerelMonitorServiceMetric
=== PAUSE TestAccDataSourceMackerelMonitorServiceMetric
=== RUN   TestAccDataSourceMackerelMonitorExternal
=== PAUSE TestAccDataSourceMackerelMonitorExternal
=== RUN   TestAccDataSourceMackerelMonitorExpression
=== PAUSE …
```

Reimplement monitors with tf-framework

---

internal/mackerel/channel.go
internal/mackerel/channel_test.go
internal/provider/data_source_mackerel_channel.go
internal/provider/data_source_mackerel_channel_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_channel.go
internal/provider/resource_mackerel_channel_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"Acc(DataSource)?MackerelChannel"'
TF_ACC=1 go test -v ./mackerel/... -run "Acc(DataSource)?MackerelChannel" -timeout 120m
2024/08/28 16:15:56 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelChannelEmail
=== PAUSE TestAccDataSourceMackerelChannelEmail
=== RUN   TestAccDataSourceMackerelChannelSlack
=== PAUSE TestAccDataSourceMackerelChannelSlack
=== RUN   TestAccDataSourceMackerelChannelWebhook
=== PAUSE TestAccDataSourceMackerelChannelWebhook
=== RUN   TestAccDataSourceMackerelChannelNotMatchAnyChannel
=== PAUSE TestAccDataSourceMackerelChannelNotMatchAnyChannel
=== RUN   TestAccMackerelChannel_Email
=== PAUSE TestAccMackerelChannel_Email …
```

Reimplement notification channels with tf-framework

---

go.mod
go.sum
internal/mackerel/dashboard.go
internal/mackerel/dashboard_test.go
internal/provider/data_source_mackerel_dashboard.go
internal/provider/data_source_mackerel_dashboard_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_dashboard.go
internal/provider/resource_mackerel_dashboard_test.go
mackerel/provider.go

```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"Acc(DataSource)?MackerelDashboard"'
TF_ACC=1 go test -v ./mackerel/... -run "Acc(DataSource)?MackerelDashboard" -timeout 120m                                                                                                          2024/09/06 12:50:53 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelDashboardGraph
=== PAUSE TestAccDataSourceMackerelDashboardGraph
=== RUN   TestAccDataSourceMackerelDashboardValue
=== PAUSE TestAccDataSourceMackerelDashboardValue
=== RUN   TestAccDataSourceMackerelDashboardMarkdown
=== PAUSE TestAccDataSourceMackerelDashboardMarkdown
=== RUN   TestAccDataSourceMackerelDashboardAlertStatus
=== PAUSE …
```

Reimplement dashboards with terraform-plugin-framework

---

internal/mackerel/downtime.go
internal/mackerel/downtime_test.go
internal/provider/data_source_mackerel_downtime.go
internal/provider/data_source_mackerel_downtime_test.go
internal/provider/provider.go
internal/provider/resource_mackerel_downtime.go
internal/provider/resource_mackerel_downtime_test.go
mackerel/provider.go

```
$ TF_ACC=1 go test -v ./mackerel/... -run "Acc(DataSource)?MackerelDowntime" -timeout 120m
2024/09/19 20:58:37 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccDataSourceMackerelDowntime
=== PAUSE TestAccDataSourceMackerelDowntime
=== RUN   TestAccDataSourceMackerelDowntimeNotMatchAnyDowntime
=== PAUSE TestAccDataSourceMackerelDowntimeNotMatchAnyDowntime
=== RUN   TestAccMackerelDowntime
=== PAUSE TestAccMackerelDowntime
=== CONT  TestAccDataSourceMackerelDowntime
=== CONT  TestAccMackerelDowntime
=== CONT  TestAccDataSourceMackerelDowntimeNotMatchAnyDowntime
--- PASS: TestAccDataSourceMackerelDowntimeNotMatchAnyDowntime (5.06s)
--- PASS: TestAccDataSourceMackerelDowntime (8.78s)
--- PASS: TestAccMackerelDowntime …
```

Reimplement downtime with terraform-plugin-framework

---

internal/provider/provider.go
internal/provider/resource_mackerel_aws_integration.go
internal/provider/resource_mackerel_aws_integration_test.go
mackerel/provider.go
mackerel/resource_mackerel_aws_integration_test.go

Part of #243 
```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='"AccMackerelAWSIntegration"'
TF_ACC=1 go test -v ./mackerel/... -run "AccMackerelAWSIntegration" -timeout 120m
2024/10/29 16:17:00 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccMackerelAWSIntegrationIAMRole
=== PAUSE TestAccMackerelAWSIntegrationIAMRole
=== RUN   TestAccMackerelAWSIntegrationCredentials
=== PAUSE TestAccMackerelAWSIntegrationCredentials
=== CONT  TestAccMackerelAWSIntegrationIAMRole
=== CONT  TestAccMackerelAWSIntegrationCredentials
--- PASS: TestAccMackerelAWSIntegrationCredentials (6.27s)
--- PASS: TestAccMackerelAWSIntegrationIAMRole (6.62s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel 7.743s …
```

Reimplement `mackerel_aws_integration` resource with terraform-plugin-framework

---

internal/planmodifierutil/nil_relaxed.go
internal/planmodifierutil/nil_relaxed_test.go

This PR introduces nil relaxed plan modifiers.
These plan modifiers improves compatibility with the terraform plugin framework and the plugin sdk.
The plugin framework strictly distinct null and empty values (e.g.,`null` and `[]`), but the sdk doesn't.
This behavior causes unexpected state updates when switching implementation.
The plan modifiers provides sdk-like behavior to plugin framework and fixes this incompatibility. 
Here's an actual usage:  https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/249

feat: add nil relaxed plan modifier

---

mackerel/resource_mackerel_downtime_test.go

```
$ make testacc TESTS='AccMackerelDowntime'
TF_ACC=1 go test -v ./mackerel/... -run AccMackerelDowntime -timeout 120m
2025/01/14 18:42:14 [INFO] mackerel: use terraform-plugin-framework based implementation
=== RUN   TestAccMackerelDowntime
=== PAUSE TestAccMackerelDowntime
=== CONT  TestAccMackerelDowntime
--- PASS: TestAccMackerelDowntime (5.87s)
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/mackerel (cached)
```

fix: downtime test

---

internal/mackerel/monitor.go
internal/mackerel/monitor_test.go
internal/provider/resource_mackerel_monitor.go
internal/provider/resource_mackerel_monitor_test.go

This PR fixes inconsistency on `mackerel_monitor` resources between SDK and framework implementations.
```
$ make testacc TESTS='Compat_MackerelMonitor'
TF_ACC=1 go test -v ./... -run Compat_MackerelMonitor -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel        0.600s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/planmodifierutil        (cached) [no tests to run]
=== RUN   TestAccCompat_MackerelMonitorResource
=== PAUSE TestAccCompat_MackerelMonitorResource
=== CONT  TestAccCompat_MackerelMonitorResource
=== RUN …
```

Fix monitor incompatibility between SDK and framework

---

docs/data-sources/monitor.md
docs/resources/monitor.md
go.mod
go.sum
internal/mackerel/monitor.go
internal/mackerel/monitor_test.go
mackerel/data_source_mackerel_monitor.go
mackerel/resource_mackerel_monitor.go
mackerel/structure_flattens.go

Hi.
This PR adds `expected_status_code` into the `mackerel_monitor` resource and data source.
See also [外形監視でOKと判定するHTTPステータスコードを選択可能にしました
](https://mackerel.io/ja/blog/entry/weekly/20241203#%E5%A4%96%E5%BD%A2%E7%9B%A3%E8%A6%96%E3%81%A7OK%E3%81%A8%E5%88%A4%E5%AE%9A%E3%81%99%E3%82%8BHTTP%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E9%81%B8%E6%8A%9E%E5%8F%AF%E8%83%BD%E3%81%AB%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F)
```console
$ make testacc TESTS='Monitor.?External'
TF_ACC=1 go test -v ./... -run Monitor.?External -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel …
```

Add expected_status_code to the external monitor resource and data source.

---

internal/mackerel/monitor.go
internal/mackerel/monitor_test.go
internal/provider/resource_mackerel_monitor.go
internal/provider/resource_mackerel_monitor_test.go
mackerel/resource_mackerel_monitor_test.go

Added support for external_status_code in external monitor in https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/258 . However, the implementation was missing and the test failed like https://github.com/mackerelio-labs/terraform-provider-mackerel/actions/runs/14212042760/job/39821559851 .
```
$ make testacc TESTS=TestAccCompat_MackerelMonitorResource
=== RUN   TestAccCompat_MackerelMonitorResource
=== PAUSE TestAccCompat_MackerelMonitorResource
=== CONT  TestAccCompat_MackerelMonitorResource
=== RUN   TestAccCompat_MackerelMonitorResource/host_metric/undefined
=== PAUSE TestAccCompat_MackerelMonitorResource/host_metric/undefined
=== RUN   TestAccCompat_MackerelMonitorResource/connectivity/undefined
=== PAUSE …
```

Add external_status_code support to internal provider resource

---

internal/provider/data_source_mackerel_monitor.go
mackerel/data_source_mackerel_monitor_test.go
mackerel/resource_mackerel_monitor_test.go

```
$ go clean -testcache
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS=TestAccDataSourceMackerelMonitorExternal
TF_ACC=1 go test -v ./... -run TestAccDataSourceMackerelMonitorExternal -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel        0.384s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/planmodifierutil        0.210s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/provider        0.499s [no tests to run]
testing: …
```

fix monitor data source

---

.github/workflows/on-pull-request.yml

Run tests on CI when get pull requests.
[ワークフローをトリガーするイベント - GitHub Docs#pull_request_target](https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target)
```
...
```

test on pull_request_target

---

internal/mackerel/monitor_test.go

```console
$ go test github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel
ok  	github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel	(cached)
```
```
...
```

Generic toPtr function

---

.github/workflows/acceptance-test.yml
.github/workflows/lint.yml
.github/workflows/release.yml
go.mod

- Update goreleaser-action to v6
- [Release v5.0.0 · goreleaser/goreleaser-action](https://github.com/goreleaser/goreleaser-action/releases/tag/v5.0.0)
- [Release v6.0.0 · goreleaser/goreleaser-action](https://github.com/goreleaser/goreleaser-action/releases/tag/v6.0.0)
- Use Go 1.24 for build & test
I checked the `actionlint` has passed.
```
...
```

goreleaser-action@v6 & Go 1.24

---

mackerel/resource_mackerel_dashboard.go
mackerel/resource_mackerel_dashboard_test.go

Refs: https://github.com/mackerelio-labs/terraform-provider-mackerel/issues/252
If you write `range {}` and empty range block in the graph block of mackerel_dashboard resource, it will cause on nil type cast and panic when you apply. The range block must contain either a relative block or an absolute block.
I change to followings : 
- Guard against type casts of nil.
- If an empty range block is specified, issue a warning.
```
$ make testacc TESTS=TestAccMackerelDashboardEmptyInvalidRange
TF_ACC=1 go test -v ./... -run TestAccMackerelDashboardEmptyInvalidRange -timeout 120m
?   	github.com/mackerelio-labs/terraform-provider-mackerel	[no test files]
PASS
ok  	github.com/mackerelio-labs/terraform-provider-mackerel/internal/mac …
```

range needs one of relative or absolute

---

.github/workflows/on-pull-request.yml

- pull_request_target trigger is not secure
- [Mitigating Attack Vectors in GitHub Workflows – Open Source Security Foundation]( https://openssf.org/blog/2024/08/12/mitigating-attack-vectors-in-github-workflows/)
- [Audit Rules - zizmor#dangerous-triggers🔗](https://woodruffw.github.io/zizmor/audits/#dangerous-triggers)
- We control to run acceptance test by setting "Require approval for all external contributors", not by trigger
- conform Go ver. other workflows
<b>attention!</b> CI should fail with the same error in the main branch https://github.com/mackerelio-labs/terraform-provider-mackerel/actions/runs/14529128108/job/40861338836
```
...
```

Secure on pull request

---

mackerel/resource_mackerel_dashboard_test.go

TestAccMackerelDashboardEmptyInvalidRange test is failing. This test hash only small value. So I remove this.
```
...
```

remove failing TestAccMackerelDashboardEmptyInvalidRange test

---

.github/workflows/on-pull-request.yml
internal/mackerel/aws_integration.go

Fixes refreshing errors caused by #257.
```
$ MACKEREL_EXPERIMENTAL_TFFRAMEWORK=1 make testacc TESTS='TestAccMackerelAWSIntegrationIAMRole'
TF_ACC=1 go test -v ./... -run TestAccMackerelAWSIntegrationIAMRole -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel        0.651s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/planmodifierutil   (cached) [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/provider        0.676s [no tests to run] …
```

fix fixnil issues

---

.github/workflows/acceptance-test.yml
.github/workflows/on-pull-request.yml
mackerel/provider.go

This pull request makes a new implementation based on [terraform-plugin-framework](https://developer.hashicorp.com/terraform/plugin/framework) the default, while making the old implementation opt-in.
The legacy implementation remains available by setting the environment variable MACKEREL_LEGACY_SDK to `1` or `true`.
```
...
```

Make framework-based implementation the default

---

mackerel/provider.go

fix: sdkflag

---

docs/resources/monitor.md

```
Error: Unsupported argument
on monitor_anolay_detection.tf line 9, in resource "mackerel_monitor" "my_anomaly_detection":
9:     maxCheckAttempts     = 3
An argument named "maxCheckAttempts" is not expected here.
```

doc: fixed the name for checking internal in mackerel_monitor's anomaly_detection.

---

docs/data-sources/service.md
docs/resources/service.md
internal/mackerel/service.go
internal/mackerel/service_test.go
internal/provider/data_source_mackerel_service.go
internal/provider/resource_mackerel_service.go
mackerel/data_source_mackerel_service.go
mackerel/data_source_mackerel_service_test.go
mackerel/resource_mackerel_service.go
mackerel/resource_mackerel_service_test.go
mackerel/structure_flattens.go

Hi, I added the computed roles field to both mackerel_service resource and data source.
This enables users to retrieve the role names defined in the service in Terraform.
```
$ make testacc TESTS="TestAcc.*Service$"
TF_ACC=1 go test -v ./... -run TestAcc.*Service$ -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel        0.007s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/planmodifierutil        0.004s [no tests to run]
PASS
ok …
```

add roles attribute to service data source and resource

---

.github/workflows/acceptance-test.yml
README.md

remove coveralls

---

internal/mackerel/dashboard.go
internal/mackerel/dashboard_test.go
internal/provider/resource_mackerel_dashboard.go
internal/provider/resource_mackerel_dashboard_test.go

Fixes #306 
```
$ make testacc TESTS='MackerelDashboard'
TF_ACC=1 go test -v ./... -run MackerelDashboard -timeout 120m
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/mackerel        0.467s [no tests to run]
PASS
ok      github.com/mackerelio-labs/terraform-provider-mackerel/internal/planmodifierutil        0.241s [no tests to run]
=== RUN   Test_MackerelDashboardDataSource_schema
=== PAUSE Test_MackerelDashboardDataSource_schema
=== RUN   Test_MackerelDashboardResource_schema
=== PAUSE Test_MackerelDashboardResource_schema
=== CONT  Test_MackerelDashboardDataSource_schema
=== CONT …
```

Fix handling of optional fields in mackerel_dashbord
