mackerelio-labs/terraform-provider-mackerel

mackerel/data_source_mackerel_channel.go, mackerel/data_source_mackerel_channel_test.go, mackerel/data_source_mackerel_downtime.go, mackerel/data_source_mackerel_downtime_test.go, mackerel/data_source_mackerel_monitor.go, mackerel/data_source_mackerel_monitor_test.go, mackerel/data_source_mackerel_notification_group.go, mackerel/data_source_mackerel_notification_group_test.go, mackerel/data_source_mackerel_role.go, mackerel/data_source_mackerel_role_metadata.go, mackerel/data_source_mackerel_role_metadata_test.go, mackerel/data_source_mackerel_role_test.go, mackerel/data_source_mackerel_service.go, mackerel/data_source_mackerel_service_metadata.go, mackerel/data_source_mackerel_service_metadata_test.go, mackerel/data_source_mackerel_service_test.go, mackerel/provider.go
=> implement datasources

LICENSE, README.md
and add an excerpt to license notation to README.md
=> Add copyright holder to license

LICENSE, README.md, go.mod, main.go
- update github action's badge
- add usage sample to prepare registration, requirements, acknowledgements
- fix path for package
=> update readme 

.github/workflows/ci.yml, README.md
use coveralls to record coverage like other OSS products
=> use coveralls

.github/workflows/release.yml, .goreleaser.yml
Add goreleaser to create release.
They are copied from 
https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.goreleaser.yml
https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml
=> add goreleaser

README.md, docs/index.md
I add document for Index of Terraform registry.
=> add document for index

docs/data-sources/monitor.md, docs/resources/monitor.md
I add documentation for monitor.
=> add docmentation for monitor

docs/data-sources/notification_group.md, docs/resources/notification_group.md
I add documentation for notification group.
=> add document for notification group

docs/data-sources/role.md, docs/data-sources/role_metadata.md, docs/data-sources/service.md, docs/data-sources/service_metadata.md, docs/resources/role.md, docs/resources/role_metadata.md, docs/resources/service.md, docs/resources/service_metadata.md
I add documentation for service and role.
- service (data_source and resource)
- service_metadata (data_source and resource)
- role (data_source and resource)
- role_metadata (data_source and resource)
=> add document for service and role

docs/data-sources/downtime.md, docs/resources/downtime.md
I add documentation for downtime.
=> add document for downtime

docs/data-sources/channel.md, docs/resources/channel.md
I add documentation for channel.
Please review 🙏
=> add documentation for channel

docs/data-sources/notification_group.md, docs/resources/notification_group.md
I fixed typo in the documentation.
Please review 🙏
=> fix typo in documentation

README.md
I added the URL for Terraform Registry of Mackerel to README.
=> add link for Terraform Registry to README

docs/index.md
I add lang setting in index.md for documentation.
Please review 🙏
=> describe lang at code block in index.md

README.md, docs/index.md
I fixed namespace in provider configuration.
=> fix source in documentation

.github/workflows/ci.yml
I changed default branch master to main.
=> change default branch master to main

docs/resources/monitor.md
fix: https://github.com/mackerelio-labs/terraform-provider-mackerel/issues/62
I fixed my mistake in documentation. Please review it 🙏
=> fix documentation about headers of external monitoring

.github/workflows/ci.yml, .gitignore, CONTRIBUTING.md, Makefile
I added CONTRIBUTING.md and Makefile to standardize test command.
=> add CONTRIBUTING.md

.github/workflows/ci.yml
- fix typo like https://github.com/mackerelio/mackerel-agent-plugins/pull/871/files
- upgrade golangci-lint-action's version to fix lint
=> fix typo in ci

.github/workflows/acceptance-test.yml
I add acceptance test to check result before release and show coverage.
```
...
```
=> run acceptance test on GitHub Actions

mackerel/structure_flattens.go
Revert https://github.com/mackerelio-labs/terraform-provider-mackerel/pull/127/commits/5ec54a2aeed89905948d2f3896c4c13ebda0ba56 because tests is failed.
https://github.com/mackerelio-labs/terraform-provider-mackerel/actions/runs/3835563400/jobs/6528899343
```zsh
...
=== CONT  TestAccMackerelDashboardAlertStatus
resource_mackerel_dashboard_test.go:214: Step 1/3 error: Check failed: Check 5/6 error: mackerel_dashboard.alertstatus: Attribute 'alert_status.#' expected "1", got "2"
--- FAIL: TestAccMackerelDashboardAlertStatus (2.88s)
=== CONT  TestAccMackerelDashboardMarkdown
resource_mackerel_dashboard_test.go:149: Step 1/3 error: Check failed: Check 5/6 error: mackerel_dashboard.markdown: Attribute 'markdown.#' expected "1", got "2"
--- FAIL: TestAccMackerelDashboardMarkdown (1.54s)
...
``` …
=> Revert `use make`

.github/workflows/lint.yml
=> workflows: rename `CI` to `Lint`

internal/validatorutil/divisible.go, internal/validatorutil/divisible_test.go
Part of #233.
This PR adds the divisible validator which checks the divisor can divide the provided value.
=> Add Divisible validator

internal/mackerel/monitor.go, internal/mackerel/monitor_test.go
Part of #233.
This PR adds data models for handling monitors.
=> Add MonitorModel

go.sum, internal/mackerel/aws_integration.go, internal/mackerel/aws_integration_test.go
=> Add model for AWS Integration
